# Generated by Django 6.1.1 on 2026-09-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='api.mechanic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='services',
            field=models.ManyToManyField(related_name='mechanics', to='api.service'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='api.service'),
            preserve_default=False,
        ),
    ]
